"""make nullable true for date fields

Revision ID: 0488f031759d
Revises: 4e525f152626
Create Date: 2026-02-14 17:37:32.206799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0488f031759d'
down_revision: Union[str, Sequence[str], None] = '4e525f152626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'sale_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sales', 'payment_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'payment_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sales', 'sale_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
